site_name: RHEL Image Mode Lifestyle, preparing for RHEL 11
docs_dir: publishing-house/spec
nav:
- Home: index.md
- Design Spec: design.md
- Modules:
  - Module 1 - Introduction: modules/module-01-introduction.md
  - Module 2 - System Updates: modules/module-02-system-updates.md
  - Module 3 - Rollback: modules/module-03-rollback.md
  - Module 4 - Openscap Hardening: modules/module-04-openscap-hardening.md
  - Module 5 - Firewall Configuration: modules/module-05-firewall-configuration.md
  - Module 6 - Containerized Apps: modules/module-06-containerized-apps.md
  - Module 7 - Sealed Images: modules/module-07-sealed-images.md
plugins:
- techdocs-core
